###############
### SOURCES ###
###############

### Do not change
source = ~/.local/share/dotfiles/default/hypr/conf/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/conf/nvidia-env.conf
source = ~/.local/share/dotfiles/default/hypr/conf/desktop-keybindings.conf
source = ~/.local/share/dotfiles/default/hypr/conf/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/conf/windowrules.conf
source = ~/.local/share/dotfiles/default/hypr/conf/layerrules.conf
source = ~/.local/share/dotfiles/current/theme/hyprland.conf

### Can change these, create more files and import here if needed
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
# source = ~/.config/hypr/my_custom_file.conf

input {
kb_layout=us, latam
kb_options=grp:win_space_toggle
}

# Screenshot a window
bind = $shiftMod, PRINT, exec, hyprshot -m window -o /home/weepbird036/Pictures
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output -o /home/weepbird036/Pictures
# Screenshot a region
bind = $mainMod, PRINT, exec, hyprshot -m region -o /home/weepbird036/Pictures

layerrule {
  name = no_anim_for_selection
  no_anim = on
  match:namespace = selection
}

exec-once = swww-daemon


